//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public string Slug { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> CeeateOnUtc { get; set; }
        public Nullable<System.DateTime> UpdateOnUtc { get; set; }
    }
}
