//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public string brand { get; set; }
        public string image { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> brandid { get; set; }
        public Nullable<System.DateTime> createdOnUtc { get; set; }
        public Nullable<System.DateTime> updateOnUtc { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> ShowOnHomePage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string slug { get; set; }
        public string description { get; set; }

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
